In [0]:
import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)
from keras.models import Sequential
from keras.layers import Dense
from keras.layers import Dropout
import tensorflow as tf
from sklearn.preprocessing import Normalizer

In [269]:
from google.colab import drive 
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [0]:
pd_dataset = pd.read_csv("/content/drive/My Drive/Colab Notebooks/INNDL/Churn.csv")

In [271]:
pd_dataset.shape

(10000, 14)

In [272]:
pd_dataset.head(10)

RowNumber  CustomerId   Surname  ...  IsActiveMember EstimatedSalary Exited
0          1    15634602  Hargrave  ...               1       101348.88      1
1          2    15647311      Hill  ...               1       112542.58      0
2          3    15619304      Onio  ...               0       113931.57      1
3          4    15701354      Boni  ...               0        93826.63      0
4          5    15737888  Mitchell  ...               1        79084.10      0
5          6    15574012       Chu  ...               0       149756.71      1
6          7    15592531  Bartlett  ...               1        10062.80      0
7          8    15656148    Obinna  ...               0       119346.88      1
8          9    15792365        He  ...               1        74940.50      0
9         10    15592389        H?  ...               1        71725.73      0

[10 rows x 14 columns]

In [0]:
pd_dataset.drop(['RowNumber','CustomerId','Surname'] ,axis=1, inplace=True)


In [274]:
pd_dataset.head()

CreditScore Geography  Gender  ...  IsActiveMember  EstimatedSalary  Exited
0          619    France  Female  ...               1        101348.88       1
1          608     Spain  Female  ...               1        112542.58       0
2          502    France  Female  ...               0        113931.57       1
3          699    France  Female  ...               0         93826.63       0
4          850     Spain  Female  ...               1         79084.10       0

[5 rows x 11 columns]

In [0]:
pd_dataset.drop(['Geography','Gender'] ,axis=1, inplace=True)

In [0]:


from tensorflow import feature_column
from tensorflow.keras import layers
from sklearn.model_selection import train_test_split

In [0]:
X = pd_dataset.drop(['Exited'] ,axis=1)

In [0]:
Y = pd_dataset[['Exited']]

In [0]:
X_train, X_test, y_train, y_test  = train_test_split(X, Y, test_size=0.2)



In [280]:
X_test.shape

(2000, 8)

In [0]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
train_normal_x=scaler.fit_transform(X_train)
test_normal_x=scaler.fit_transform(X_test)

In [0]:
#Initialize Sequential Graph (model)
model = tf.keras.Sequential()

#model.add(tf.keras.layers.Dense(1, input_shape=(10,)))
#Add Dense layer for prediction - Keras declares weights and bias automatically
model.add(tf.keras.layers.Dense(16, input_shape=(8,), activation='relu'))
model.add(tf.keras.layers.Dense(32, activation='relu'))

model.add(tf.keras.layers.Dense(2, activation='softmax'))



In [0]:
#Compile the model - add Loss and Gradient Descent optimizer
model.compile(optimizer='sgd', loss='mse',metrics=['accuracy'])

#Normalize the data
#model.add(tf.keras.layers.BatchNormalization())

In [284]:
y_train

Exited
2254       0
7456       0
4839       1
4755       0
1562       1
...      ...
9940       0
7055       0
7515       0
697        1
8638       0

[8000 rows x 1 columns]

In [0]:
y_train = tf.keras.utils.to_categorical(y_train, num_classes=2)

In [286]:
y_train

array([[1., 0.],
       [1., 0.],
       [0., 1.],
       ...,
       [1., 0.],
       [0., 1.],
       [1., 0.]], dtype=float32)

### I have tried mutiple option to create a model & demonstrated the final one


In [287]:
model.fit(train_normal_x, y_train,
          epochs=100)

Epoch 1/100
250/250 [==============================] - 0s 1ms/step - loss: 0.1852 - accuracy: 0.7449
Epoch 2/100
250/250 [==============================] - 0s 1ms/step - loss: 0.1558 - accuracy: 0.7931
Epoch 3/100
250/250 [==============================] - 0s 1ms/step - loss: 0.1524 - accuracy: 0.7931
Epoch 4/100
250/250 [==============================] - 0s 1ms/step - loss: 0.1501 - accuracy: 0.7939
Epoch 5/100
250/250 [==============================] - 0s 1ms/step - loss: 0.1481 - accuracy: 0.7945
Epoch 6/100
250/250 [==============================] - 0s 1ms/step - loss: 0.1465 - accuracy: 0.7962
Epoch 7/100
250/250 [==============================] - 0s 1ms/step - loss: 0.1451 - accuracy: 0.7971
Epoch 8/100
250/250 [==============================] - 0s 1ms/step - loss: 0.1439 - accuracy: 0.7984
Epoch 9/100
250/250 [==============================] - 0s 1ms/step - loss: 0.1429 - accuracy: 0.7981
Epoch 10/100
250/250 [==============================] - 0s 1ms/step - loss: 0.1420 - accura

In [288]:
model.summary()

Model: "sequential_20"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_58 (Dense)             (None, 16)                144       
_________________________________________________________________
dense_59 (Dense)             (None, 32)                544       
_________________________________________________________________
dense_60 (Dense)             (None, 2)                 66        
Total params: 754
Trainable params: 754
Non-trainable params: 0
_________________________________________________________________


In [289]:
predict=model.predict(X_test)
predict

array([[0., 1.],
       [0., 1.],
       [0., 1.],
       ...,
       [0., 1.],
       [0., 1.],
       [0., 1.]], dtype=float32)

In [290]:
loss_and_acc = model.evaluate(train_normal_x, y_train)
print(loss_and_acc)

250/250 [==============================] - 0s 1ms/step - loss: 0.1070 - accuracy: 0.8586
[0.10699380934238434, 0.8586249947547913]


In [291]:
y_pred = model.predict(test_normal_x, verbose=0)
y_pred_classes = model.predict_classes(test_normal_x, verbose=0)
print(y_pred)

[[0.75147825 0.24852179]
 [0.9975298  0.00247025]
 [0.46066692 0.53933305]
 ...
 [0.8740146  0.12598534]
 [0.9642433  0.03575673]
 [0.17456305 0.82543695]]


In [0]:
y_pred_final = [1 if x[1] >= .5 else 0 for x in y_pred]

In [293]:
print(np.transpose(np.matrix(y_pred_final)))

[[0]
 [0]
 [1]
 ...
 [0]
 [0]
 [1]]
